# can interface name as shown in ifconfig -a
can_device: "can0"
# can bridge receive topic
can_rx_topic: "/can/received_messages"
# can bridge transmit topic
can_tx_ropic: "/can/sent_messages"
# axis state update in Hz
update_rate: 10
# engage axises on startup
engage_on_startup: true
# minimum axis velocity - e.g if set to 1.0 target velocity will be set to this value
# for both positive and negative velocities (0.5 will become 1.0, -0.5 will become -1.0)
axis_min_velocity: 1.5
# array of strings representing names of axises
axis_names: ["left_wheel", "right_wheel"]
# array of ints representing can ids of axises
axis_can_ids: [1, 2]
# array of axis directions
axis_directions: ["backward", "forward"]
